export const SET_RECOMMEND_MUSICLIST = 'SET_RECOMMEND_MUSICLIST'

export const SET_RECOMMEND_PRIVATE = 'SET_RECOMMEND_PRIVATE'

export const SET_RECOMMEND_MV = 'SET_RECOMMEND_MV'

export const SET_RECOMMEND_BANNER = 'SET_RECOMMEND_BANNER'

export const SET_TOP_MV = 'SET_TOP_MV'

export const SET_MUSICLISTDETAIL_SHOWLIST = 'SET_MUSICLISTDETAIL_SHOWLIST'

export const SET_MUSICLISTDETAIL_SHOW = 'SET_MUSICLISTDETAIL_SHOW'

export const SET_MUSICLISTDETAIL_COPYWRITE = 'SET_MUSICLISTDETAIL_COPYWRITE'

export const SET_ALBUMDETAIL_SHOWLIST = 'SET_ALBUMDETAIL_SHOWLIST'

export const SET_ALBUMDETAIL_SHOW = 'SET_ALBUMDETAIL_SHOW'

export const SET_PLAYER_STATE = 'SET_PLAYER_STATE'

export const SET_PLAYER_FULLSCREEN = 'SET_PLAYER_FULLSCREEN'

export const SET_PLAYER_PLAYLIST = 'SET_PLAYER_PLAYLIST'

export const SET_PLAYER_MODE = 'SET_PLAYER_MODE'

export const SET_PLAYER_CURRENTINDEX = 'SET_PLAYER_CURRENTINDEX'

export const SET_MVDETAIL_MVID = 'SET_MVDETAIL_MVID'

export const SET_MVDETAIL_SHOW = 'SET_MVDETAIL_SHOW'

export const SET_SEARCH_SHOW = 'SET_SEARCH_SHOW'

export const SET_SINGER_ARTIST = 'SET_SINGER_ARTIST'

export const SET_SINGER_SHOW = 'SET_SINGER_SHOW'

export const SET_SINGER_LIST = 'SET_SINGER_LIST'
